version: '2'

services:

  wordpress:
    image: emcniece/wp-php7-nginx
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress

  mysql:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress